[assembly: System.Reflection.AssemblyCompany("Lynx.Config")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyProduct("Lynx.Config")]
[assembly: System.Reflection.AssemblyTitle("Lynx.Config")]
[assembly: System.Reflection.AssemblyVersion("1.0.*")]