[assembly: System.Reflection.AssemblyCompany("Lynx.Logger")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyProduct("Lynx.Logger")]
[assembly: System.Reflection.AssemblyTitle("Lynx.Logger")]
[assembly: System.Reflection.AssemblyVersion("1.0.*")]